# NumPy 배열의 기본

파이썬(Python)의 데이터 조작은 NumPy 배열 조작과 거의 동의어입니다. Pandas([Part 3](03.00-Introduction-to-Pandas.ipynb))와 같은 최신 도구도 NumPy 배열을 기반으로 구축되었습니다.
이번 장에서는 NumPy 배열 조작을 사용하여 데이터 및 하위 배열에 액세스하고 배열을 분할, 재구성 및 결합하는 몇 가지 예를 제시합니다.
여기에 표시된 작업 유형은 다소 무미건조하고 현학적인 것처럼 보일 수 있지만 이 책 전체에서 사용되는 다른 많은 예제의 구성 요소를 구성합니다.
그들을 잘 알아가세요!

여기서는 기본 배열 조작의 몇 가지 범주를 다루겠습니다.

- *배열의 속성*: 배열의 크기, 모양, 메모리 소비 및 데이터 유형 결정
- *배열 인덱싱*: 개별 배열 요소의 값 가져오기 및 설정
- *배열 분할*: 더 큰 배열 내에서 더 작은 하위 배열 가져오기 및 설정
- *배열 재구성*: 주어진 배열의 모양 변경
- *배열 결합 및 분할*: 여러 배열을 하나로 결합하고 하나의 배열을 여러 개로 분할

## NumPy 배열 속성

먼저 몇 가지 유용한 배열 속성에 대해 논의해 보겠습니다.
1차원, 2차원, 3차원의 무작위 배열을 정의하는 것부터 시작하겠습니다.
우리는 NumPy의 난수 생성기를 사용할 것입니다. 이 생성기는 이 코드가 실행될 때마다 동일한 난수 배열이 생성되도록 하기 위해 설정된 값으로 *시드*됩니다.

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)  # seed for reproducibility

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array

각 배열에는 `ndim`(차원 수), `shape`(각 차원의 크기), `size`(배열의 전체 크기) 및 `dtype`(각 요소의 유형)을 포함한 속성이 있습니다.

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


데이터 유형에 대한 자세한 내용은 [파이썬(Python)의 데이터 유형 이해](02.01-Understanding-Data-Types.ipynb)를 참조하세요.

## 배열 인덱싱: 단일 요소에 액세스

파이썬(Python)의 표준 목록 인덱싱에 익숙하다면 NumPy의 인덱싱이 매우 친숙하게 느껴질 것입니다.
1차원 배열에서 $i^{th}$ 값(0부터 계산)은 파이썬(Python) 목록과 마찬가지로 대괄호 안에 원하는 인덱스를 지정하여 액세스할 수 있습니다.

In [3]:
x1

array([9, 4, 0, 3, 8, 6])

In [4]:
x1[0]

9

In [5]:
x1[4]

8

배열 끝에서부터 색인을 생성하려면 음수 색인을 사용할 수 있습니다.

In [6]:
x1[-1]

6

In [7]:
x1[-2]

8

다차원 배열에서는 쉼표로 구분된 `(행, 열)` 튜플을 사용하여 항목에 액세스할 수 있습니다.

In [8]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [9]:
x2[0, 0]

3

In [10]:
x2[2, 0]

0

In [11]:
x2[2, -1]

9

위의 인덱스 표기법을 사용하여 값을 수정할 수도 있습니다.

In [12]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

파이썬(Python) 목록과 달리 NumPy 배열은 고정된 유형을 가집니다.
예를 들어 부동 소수점 값을 정수 배열에 삽입하려고 하면 값이 자동으로 잘립니다. 이 행동을 모르고 버리지 마십시오!

In [13]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 4, 0, 3, 8, 6])

## 배열 슬라이싱: 하위 배열 액세스

대괄호를 사용하여 개별 배열 요소에 액세스할 수 있는 것처럼 대괄호를 사용하여 콜론(`:`) 문자로 표시된 *슬라이스* 표기법으로 하위 배열에 액세스할 수도 있습니다.
NumPy 슬라이싱 구문은 표준 파이썬(Python) 목록의 구문을 따릅니다. 배열 'x'의 조각에 접근하려면 다음을 사용하세요:
``파이썬
x[시작:중지:단계]
````
이들 중 하나라도 지정되지 않은 경우 기본값은 `start=0`, `stop=<크기 크기>`, `step=1` 값입니다.
한 차원과 여러 차원에서 하위 배열에 액세스하는 몇 가지 예를 살펴보겠습니다.

### 1차원 하위 ​​배열

다음은 1차원 하위 ​​배열의 요소에 액세스하는 몇 가지 예입니다.

In [14]:
x1

array([3, 4, 0, 3, 8, 6])

In [15]:
x1[:3]  # first three elements

array([3, 4, 0])

In [16]:
x1[3:]  # elements after index 3

array([3, 8, 6])

In [17]:
x1[1:4]  # middle subarray

array([4, 0, 3])

In [18]:
x1[::2]  # every second element

array([3, 0, 8])

In [19]:
x1[1::2]  # every second element, starting at index 1

array([4, 3, 6])

잠재적으로 혼란스러운 경우는 `step` 값이 음수인 경우입니다.
이 경우 `start`와 `stop`의 기본값이 교체됩니다.
이는 배열을 뒤집는 편리한 방법이 됩니다.

In [20]:
x1[::-1]  # all elements, reversed

array([6, 8, 3, 0, 4, 3])

In [21]:
x1[4::-2]  # every second element from index 4, reversed

array([8, 0, 3])

### 다차원 하위 ​​배열

다차원 조각은 여러 조각이 쉼표로 구분되어 동일한 방식으로 작동합니다.
예를 들어:

In [22]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [23]:
x2[:2, :3]  # first two rows & three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [24]:
x2[:3, ::2]  # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [25]:
x2[::-1, ::-1]  # all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

#### 배열 행 및 열에 액세스하기

일반적으로 필요한 루틴 중 하나는 배열의 단일 행이나 열에 액세스하는 것입니다.
이는 단일 콜론(`:`)으로 표시된 빈 슬라이스를 사용하여 인덱싱과 슬라이싱을 결합하여 수행할 수 있습니다.

In [26]:
x2[:, 0]  # first column of x2

array([12,  4,  0])

In [27]:
x2[0, :]  # first row of x2

array([12,  1,  3,  7])

행 액세스의 경우 보다 간결한 구문을 위해 빈 조각을 생략할 수 있습니다.

In [28]:
x2[0]  # equivalent to x2[0, :]

array([12,  1,  3,  7])

### 복사하지 않는 뷰로서의 하위 배열

파이썬(Python) 목록 슬라이스와 달리 NumPy 배열 슬라이스는 배열 데이터의 *사본*이 아닌 *뷰*로 반환됩니다.
이전의 2차원 배열을 생각해 보세요.

In [29]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


여기서 $2 \times 2$ 하위 배열을 추출해 보겠습니다.

In [30]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]


이제 이 하위 배열을 수정하면 원래 배열이 변경된 것을 볼 수 있습니다! 관찰하다:

In [31]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [32]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


일부 사용자는 이것이 놀랍다고 생각할 수도 있지만 이점이 있을 수 있습니다. 예를 들어 대규모 데이터세트로 작업할 때 기본 데이터 버퍼를 복사할 필요 없이 이러한 데이터세트의 일부에 액세스하고 처리할 수 있습니다.

### 배열 복사본 만들기

배열 뷰의 뛰어난 기능에도 불구하고 때로는 배열이나 하위 배열 내의 데이터를 명시적으로 복사하는 것이 유용할 때가 있습니다. 이 작업은 `복사` 방법을 사용하여 가장 쉽게 수행할 수 있습니다.

In [33]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


이제 이 하위 배열을 수정하면 원래 배열은 건드리지 않습니다.

In [34]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [35]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## 배열 재구성

또 다른 유용한 작업 유형은 'reshape' 메서드를 사용하여 수행할 수 있는 배열 재구성입니다.
예를 들어 $3 \times 3$ 그리드에 1부터 9까지의 숫자를 넣으려면 다음과 같이 하면 됩니다:

In [36]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


이것이 작동하려면 초기 배열의 크기가 재구성된 배열의 크기와 일치해야 하며 대부분의 경우 `reshape` 메소드는 초기 배열의 복사 없음 보기를 반환합니다.

일반적인 재형성 작업은 1차원 배열을 2차원 행 또는 열 행렬로 변환하는 것입니다.

In [37]:
x = np.array([1, 2, 3])
x.reshape((1, 3))  # row vector via reshape

array([[1, 2, 3]])

In [38]:
x.reshape((3, 1))  # column vector via reshape

array([[1],
       [2],
       [3]])

이에 대한 편리한 약칭은 슬라이싱 구문에서 `np.newaxis`를 사용하는 것입니다:

In [39]:
x[np.newaxis, :]  # row vector via newaxis

array([[1, 2, 3]])

In [40]:
x[:, np.newaxis]  # column vector via newaxis

array([[1],
       [2],
       [3]])

이는 이 책의 나머지 부분에서 자주 활용하게 될 패턴입니다.

## 배열 연결 및 분할

이전 루틴은 모두 단일 어레이에서 작동했습니다. NumPy는 또한 여러 배열을 하나로 결합하고 반대로 단일 배열을 여러 배열로 분할하는 도구를 제공합니다.

### 배열 연결

NumPy에서 두 배열의 연결 또는 결합은 주로 `np.concatenate`, `np.vstack` 및 `np.hstack` 루틴을 사용하여 수행됩니다.
`np.concatenate`는 여기에서 볼 수 있듯이 첫 번째 인수로 튜플이나 배열 목록을 사용합니다.

In [41]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

한 번에 두 개 이상의 배열을 연결할 수도 있습니다.

In [42]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


그리고 2차원 배열에도 사용할 수 있습니다.

In [43]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [44]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

혼합 차원 배열로 작업하려면 `np.vstack`(수직 스택) 및 `np.hstack`(수평 스택) 함수를 사용하는 것이 더 명확할 수 있습니다.

In [46]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

마찬가지로, 고차원 배열의 경우 `np.dstack`은 세 번째 축을 따라 배열을 쌓습니다.

### 배열 분할

연결의 반대는 분할이며, 이는 `np.split`, `np.hsplit` 및 `np.vsplit` 함수에 의해 구현됩니다.  이들 각각에 대해 분할 지점을 제공하는 인덱스 목록을 전달할 수 있습니다.

In [48]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


*N* 분할 지점은 *N* + 1 하위 배열로 이어집니다.
관련 함수 `np.hsplit`과 `np.vsplit`은 유사합니다:

In [49]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [51]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


마찬가지로, 고차원 배열의 경우 `np.dsplit`은 세 번째 축을 따라 배열을 분할합니다.